<?php
include 'header.php';
?>

<body class="manage-tournament-body">
    <!-- Animated background effects -->
    <div class="bg-effect bg-effect-1"></div>
    <div class="bg-effect bg-effect-2"></div>

    <div class="container">
        <!-- Header -->
        <div class="header">
            <h1>Tournament Management</h1>
            <p>Select a category to manage your gaming tournament</p>
        </div>

        <!-- Category Grid -->
        <div class="category-grid" id="categoryGrid">
            <!-- Categories will be generated by JavaScript -->
        </div>

        <!-- Management Panel -->
        <div class="management-panel" id="managementPanel">
            <div class="panel-header">
                <div class="panel-header-top">
                    <div>
                        <h2 id="panelTitle">Manage Category</h2>
                        <div class="panel-header-info" id="panelInfo">0 items total</div>
                    </div>
                    <button class="close-btn" onclick="closePanel()">
                        <svg class="icon" viewBox="0 0 24 24">
                            <path d="M18 6L6 18M6 6l12 12"/>
                        </svg>
                    </button>
                </div>
                <div class="panel-controls">
                    <div class="search-wrapper">
                        <svg class="search-icon" viewBox="0 0 24 24">
                            <circle cx="11" cy="11" r="8"/>
                            <path d="m21 21-4.35-4.35"/>
                        </svg>
                        <input type="text" class="search-input" id="searchInput" placeholder="Search..." oninput="filterItems()">
                    </div>
                    <button class="add-btn" onclick="showForm()">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M12 5v14M5 12h14"/>
                        </svg>
                        Add New
                    </button>
                </div>
            </div>
            <div class="panel-content">
                <!-- Form -->
                <div class="item-form" id="itemForm">
                    <h3 id="formTitle">Add New Item</h3>
                    <div class="form-group">
                        <input type="text" class="form-input" id="itemName" placeholder="Name">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-input" id="itemDetails" placeholder="Details">
                    </div>
                    <div class="form-actions">
                        <button class="btn-primary" onclick="submitForm()">Add</button>
                        <button class="btn-secondary" onclick="cancelForm()">Cancel</button>
                    </div>
                </div>

                <!-- Items List -->
                <div class="items-list" id="itemsList">
                    <!-- Items will be generated by JavaScript -->
                </div>
            </div>
        </div>

        <!-- Stats Grid -->
        <div class="stats-grid" id="statsGrid">
            <!-- Stats will be generated by JavaScript -->
        </div>
    </div>

    <script>
        // Data structure
        const categories = [
            {
                id: 'tournaments',
                title: 'Tournaments',
                description: 'Manage tournament events and competitions',
                icon: 'M8 21l4-4m0 0l4 4m-4-4v9m9-20h2a2 2 0 012 2v16a2 2 0 01-2 2H3a2 2 0 01-2-2V3a2 2 0 012-2h2m16 0v4H3V1m18 0h-2m-7 4h2',
                gradient: 'linear-gradient(to bottom right, #eab308, #f97316)',
                color: 'cyan'
            },
            {
                id: 'teams',
                title: 'Teams',
                description: 'Organize teams and rosters',
                icon: 'M12 2v8m0 0l-4-4m4 4l4-4m-4 4v8m0 0l-4-4m4 4l4-4',
                gradient: 'linear-gradient(to bottom right, #3b82f6, #06b6d4)',
                color: 'blue'
            },
            {
                id: 'players',
                title: 'Players',
                description: 'Manage player profiles and stats',
                icon: 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z',
                gradient: 'linear-gradient(to bottom right, #a855f7, #ec4899)',
                color: 'purple'
            },
            {
                id: 'matches',
                title: 'Matches',
                description: 'Schedule and track game matches',
                icon: 'M21 3l-9 9-9-9m18 0v18',
                gradient: 'linear-gradient(to bottom right, #ef4444, #f97316)',
                color: 'cyan'
            },
            {
                id: 'events',
                title: 'Events',
                description: 'Plan and coordinate gaming events',
                icon: 'M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z',
                gradient: 'linear-gradient(to bottom right, #22c55e, #10b981)',
                color: 'green'
            },
            {
                id: 'brackets',
                title: 'Brackets',
                description: 'Create and manage tournament brackets',
                icon: 'M12 2L2 19.5h20L12 2z',
                gradient: 'linear-gradient(to bottom right, #06b6d4, #3b82f6)',
                color: 'blue'
            },
            {
                id: 'leaderboards',
                title: 'Leaderboards',
                description: 'Track rankings and achievements',
                icon: 'M5 3v18l7-5 7 5V3H5z',
                gradient: 'linear-gradient(to bottom right, #eab308, #f59e0b)',
                color: 'cyan'
            },
            {
                id: 'sponsors',
                title: 'Sponsors',
                description: 'Manage sponsors and partnerships',
                icon: 'M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222',
                gradient: 'linear-gradient(to bottom right, #6366f1, #a855f7)',
                color: 'purple'
            }
        ];

        const mockData = {
            'Tournaments': [
                { id: '1', name: 'Summer Championship 2026', details: 'Battle Royale - 128 players', status: 'Active' },
                { id: '2', name: 'Winter League Finals', details: 'Team-based competition', status: 'Upcoming' },
                { id: '3', name: 'Spring Invitational', details: 'Invitation only event', status: 'Completed' }
            ],
            'Teams': [
                { id: '1', name: 'Cyber Dragons', details: '5 members - Rank #3', status: 'Active' },
                { id: '2', name: 'Shadow Wolves', details: '5 members - Rank #7', status: 'Active' },
                { id: '3', name: 'Phoenix Rising', details: '4 members - Rank #12', status: 'Recruiting' }
            ],
            'Players': [
                { id: '1', name: 'ProGamer123', details: 'Level 45 - 2.3K/D Ratio', status: 'Online' },
                { id: '2', name: 'ShadowNinja', details: 'Level 38 - 1.8K/D Ratio', status: 'Offline' },
                { id: '3', name: 'EliteSniper', details: 'Level 52 - 3.1K/D Ratio', status: 'In Match' }
            ],
            'Matches': [
                { id: '1', name: 'Dragons vs Wolves', details: 'Best of 5 - Map: Inferno', status: 'Live' },
                { id: '2', name: 'Phoenix vs Knights', details: 'Best of 3 - Map: Desert Storm', status: 'Scheduled' },
                { id: '3', name: 'Titans vs Legends', details: 'Best of 5 - Map: Arctic Base', status: 'Completed' }
            ],
            'Events': [
                { id: '1', name: 'Monthly Cup', details: 'Jan 15, 2026 - Online', status: 'Upcoming' },
                { id: '2', name: 'LAN Finals', details: 'Feb 20-22, 2026 - New York', status: 'Registration Open' },
                { id: '3', name: 'Community Tournament', details: 'Dec 10, 2025 - Online', status: 'Completed' }
            ],
            'Brackets': [
                { id: '1', name: 'Main Championship', details: 'Single Elimination - 32 teams', status: 'In Progress' },
                { id: '2', name: 'Losers Bracket', details: 'Double Elimination - 16 teams', status: 'Round 2' },
                { id: '3', name: 'Qualifiers', details: 'Swiss System - 64 teams', status: 'Completed' }
            ],
            'Leaderboards': [
                { id: '1', name: 'Global Rankings', details: 'All regions - Weekly reset', status: 'Active' },
                { id: '2', name: 'Regional Standings', details: 'NA/EU/ASIA divisions', status: 'Active' },
                { id: '3', name: 'Season 5 Final', details: 'End of season rankings', status: 'Archived' }
            ],
            'Sponsors': [
                { id: '1', name: 'TechGear Pro', details: 'Hardware Partner - $50K', status: 'Active' },
                { id: '2', name: 'Energy Drink X', details: 'Beverage Sponsor - $30K', status: 'Active' },
                { id: '3', name: 'Gaming Chairs Inc', details: 'Furniture Partner - $20K', status: 'Pending' }
            ]
        };

        let currentCategory = null;
        let categoryData = JSON.parse(JSON.stringify(mockData));
        let editingItemId = null;

        // Initialize
        function init() {
            renderCategories();
            renderStats();
        }

        // Render category cards
        function renderCategories() {
            const grid = document.getElementById('categoryGrid');
            grid.innerHTML = categories.map(cat => `
                <div class="category-card" onclick="selectCategory('${cat.title}')" style="--gradient: ${cat.gradient}">
                    <div style="background: ${cat.gradient}; position: absolute; top: 0; right: 0; width: 150px; height: 150px; opacity: 0.2; filter: blur(50px);"></div>
                    <div class="icon-wrapper">
                        <svg class="icon" viewBox="0 0 24 24">
                            <path d="${cat.icon}"/>
                        </svg>
                    </div>
                    <h3>${cat.title}</h3>
                    <p>${cat.description}</p>
                </div>
            `).join('');
        }

        // Select category
        function selectCategory(title) {
            currentCategory = title;
            document.getElementById('categoryGrid').classList.add('hidden');
            document.getElementById('statsGrid').classList.add('hidden');
            document.getElementById('managementPanel').classList.add('active');
            document.getElementById('panelTitle').textContent = `Manage ${title}`;
            renderItems();
        }

        // Close panel
        function closePanel() {
            currentCategory = null;
            editingItemId = null;
            document.getElementById('categoryGrid').classList.remove('hidden');
            document.getElementById('statsGrid').classList.remove('hidden');
            document.getElementById('managementPanel').classList.remove('active');
            document.getElementById('itemForm').classList.remove('active');
            document.getElementById('searchInput').value = '';
        }

        // Render items
        function renderItems() {
            const items = categoryData[currentCategory] || [];
            const searchQuery = document.getElementById('searchInput').value.toLowerCase();
            const filteredItems = items.filter(item => 
                item.name.toLowerCase().includes(searchQuery) ||
                item.details.toLowerCase().includes(searchQuery)
            );

            document.getElementById('panelInfo').textContent = `${items.length} ${items.length === 1 ? 'item' : 'items'} total`;

            const listEl = document.getElementById('itemsList');
            
            if (filteredItems.length === 0) {
                listEl.innerHTML = `
                    <div class="empty-state">
                        <div class="empty-icon">
                            <svg viewBox="0 0 24 24">
                                <circle cx="11" cy="11" r="8"/>
                                <path d="m21 21-4.35-4.35"/>
                            </svg>
                        </div>
                        <p>${searchQuery ? 'No items found' : 'No items yet. Add your first item!'}</p>
                    </div>
                `;
                return;
            }

            listEl.innerHTML = filteredItems.map(item => `
                <div class="item-card">
                    <div class="item-info">
                        <h4>${item.name}</h4>
                        <p>${item.details}</p>
                        ${item.status ? `<span class="item-status">${item.status}</span>` : ''}
                    </div>
                    <div class="item-actions">
                        <button class="action-btn edit" onclick="editItem('${item.id}')">
                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/>
                                <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>
                            </svg>
                        </button>
                        <button class="action-btn delete" onclick="deleteItem('${item.id}')">
                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path d="M3 6h18M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/>
                            </svg>
                        </button>
                    </div>
                </div>
            `).join('');
        }

        // Filter items
        function filterItems() {
            renderItems();
        }

        // Show form
        function showForm() {
            editingItemId = null;
            document.getElementById('formTitle').textContent = 'Add New Item';
            document.getElementById('itemName').value = '';
            document.getElementById('itemDetails').value = '';
            document.getElementById('itemForm').classList.add('active');
            document.querySelector('.btn-primary').textContent = 'Add';
        }

        // Edit item
        function editItem(id) {
            const items = categoryData[currentCategory];
            const item = items.find(i => i.id === id);
            if (!item) return;

            editingItemId = id;
            document.getElementById('formTitle').textContent = 'Edit Item';
            document.getElementById('itemName').value = item.name;
            document.getElementById('itemDetails').value = item.details;
            document.getElementById('itemForm').classList.add('active');
            document.querySelector('.btn-primary').textContent = 'Update';
        }

        // Submit form
        function submitForm() {
            const name = document.getElementById('itemName').value.trim();
            const details = document.getElementById('itemDetails').value.trim();

            if (!name) return;

            if (editingItemId) {
                // Update existing item
                const items = categoryData[currentCategory];
                const index = items.findIndex(i => i.id === editingItemId);
                if (index !== -1) {
                    items[index].name = name;
                    items[index].details = details;
                }
            } else {
                // Add new item
                const newItem = {
                    id: Date.now().toString(),
                    name: name,
                    details: details,
                    status: 'Active'
                };
                categoryData[currentCategory].push(newItem);
            }

            cancelForm();
            renderItems();
            renderStats();
        }

        // Cancel form
        function cancelForm() {
            editingItemId = null;
            document.getElementById('itemForm').classList.remove('active');
            document.getElementById('itemName').value = '';
            document.getElementById('itemDetails').value = '';
        }

        // Delete item
        function deleteItem(id) {
            if (!confirm('Are you sure you want to delete this item?')) return;
            
            categoryData[currentCategory] = categoryData[currentCategory].filter(i => i.id !== id);
            renderItems();
            renderStats();
        }

        // Render stats
        function renderStats() {
            const statsGrid = document.getElementById('statsGrid');
            statsGrid.innerHTML = `
                <div class="stat-card">
                    <div class="stat-value cyan">${categoryData['Tournaments']?.length || 0}</div>
                    <div class="stat-label">Active Tournaments</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value purple">${categoryData['Teams']?.length || 0}</div>
                    <div class="stat-label">Registered Teams</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value blue">${categoryData['Players']?.length || 0}</div>
                    <div class="stat-label">Total Players</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value green">${categoryData['Matches']?.length || 0}</div>
                    <div class="stat-label">Scheduled Matches</div>
                </div>
            `;
        }

        // Initialize on load
        init();
    </script>
</body>
</html>
